---
- hosts: edge
  name: Stage edge workload
  become: yes
  gather_facts: true
  vars:
     userid: 0
     domain: rhnaps.io
     prefix: example

  tasks:
  - name: Pull image from OpenShift registry
    containers.podman.podman_image:
      name: registry-openshift-image-registry.apps.{{ prefix }}.{{ domain }}/edge-{{ userid }}/edge
      validate_certs: no
      pull: yes
      force: yes
      tag: latest 

  - name: Create container definitions for container image
    containers.podman.podman_container:
      state: present
      name: edge
      image: "registry-openshift-image-registry.apps.{{ prefix }}.{{ domain }}/edge-{{ userid }}/edge"
      ports: "80:8080"
      label: "io.containers.autoupdate=image"
  
  - name: Generate systemd unit files
    shell:
      cmd: "podman generate systemd --name edge --new > /etc/systemd/system/container-edge.service"
      creates: /etc/systemd/system/edge.service

  - name: Ensure that edge service is enabled and started
    service:
       name: container-edge
       state: restarted
       enabled: yes

