---
- hosts: edge
  name: Stage edge workload
  gather_facts: true
  become: yes
  vars:
     userid: 0
     domain: rhnaps.io
     prefix: example

  tasks:
  - name: Log into OpenShift registry (get temporary token)
    shell:
      cmd: "podman login -u user{{ userid }} -p {{ token }} registry-openshift-image-registry.apps.{{ prefix }}.{{ domain }} --tls-verify=false"
