---
- hosts: edge
  name: Stage edge workload
  gather_facts: true
  vars:
     userid: 0
     domain: rhnaps.io
     prefix: example

  tasks:
  - name: Log into OpenShift registry (get temporary token)
    containers.podman.podman_login:
      registry: registry-openshift-image-registry.apps.{{ prefix }}.{{ domain }}
      tlsverify: no
      username: "user{{ userid }}"
      password: "{{ token }}"
      authfile: /root/auth.json

