---
- hosts: edge
  name: Stage edge workload
  gather_facts: true
  become: yes
  nolog: true
  vars:
     userid: 0
     domain: rhnaps.io
     prefix: example

  tasks:

  - name: Log into OpenShift registry (get temporary token)
    containers.podman.podman_login:
      registry: 'https://registry-openshift-image-registry.apps.{{ prefix }}.{{ domain }}'
      tlsverify: false
      username: 'user{{ userid }}'
      password: '{{ token }}'

